# Generated by Django 4.2.7 on 2024-01-04 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='Мужской пол', max_length=40, verbose_name='Выберите пол')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=20, null=True, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_car', models.CharField(max_length=20, verbose_name='марка')),
                ('model_car', models.CharField(max_length=20, verbose_name='модель')),
                ('color_car', models.CharField(max_length=20, verbose_name='цвет кузова')),
                ('state_number', models.CharField(max_length=20, unique=True, verbose_name='государственный номер')),
                ('in_parking', models.BooleanField(verbose_name='статуса автомобиля на стоянке')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='parking.client', verbose_name='владелец автомобиля')),
            ],
        ),
    ]
