# Generated by Django 4.2.7 on 2023-12-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('sex', models.CharField(max_length=5, verbose_name='пол')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=5, null=True, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_car', models.CharField(max_length=20, verbose_name='марка')),
                ('model_car', models.CharField(max_length=20, verbose_name='модель')),
                ('color_car', models.CharField(max_length=20, verbose_name='цвет кузова')),
                ('state_number', models.CharField(max_length=20, unique=True, verbose_name='государственный номер')),
                ('in_parking', models.BooleanField(verbose_name='статуса автомобиля на стоянке')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='parking.client')),
            ],
        ),
    ]
