# Generated by Django 4.2.7 on 2023-12-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_client_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cars',
            field=models.CharField(max_length=20, null=True, verbose_name='автотранспорт клиента'),
        ),
    ]
